[package]
name = "client"
edition = "2021"
version.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
bevy = {workspace = true}
shared = {path = "../shared", features = ["gui"]}
lightyear.workspace = true
avian2d.workspace = true
serde.workspace = true
leafwing-input-manager.workspace = true

[lints]
workspace = true
