name: Publish server docker container
on:
  # Trigger this workflow when a tag is pushed in the format `v1.2.3`.
  push:
    tags:
      - 'v*'
  # Or trigger this workflow manually via workflow dispatch.
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in the format `v1.2.3`'
        required: true
        type: string

# This is configured to push to the edgegap container registry, where
# our server is deployed.
# Remember to set your DOCKER_PASSWORD secret environment variable on
# github's settings page for your repo, so you can auth with the edgegap registry.
env:
  IMAGE_NAME: "metabrew-kfk5fha5fsct/spaceships-server"
  DOCKER_REGISTRY: "registry.edgegap.com"
  DOCKER_USERNAME: "robot$metabrew-kfk5fha5fsct+client-push"
  # Remember to set ${{ secrets.DOCKER_PASSWORD }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME}}

      - name: build image
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./server/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
